# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_relatorio_chamados_fechados.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_TelaRelatoriosChamadosFechados(object):
    def setupUi(self, TelaRelatoriosChamadosFechados):
        if not TelaRelatoriosChamadosFechados.objectName():
            TelaRelatoriosChamadosFechados.setObjectName(u"TelaRelatoriosChamadosFechados")
        TelaRelatoriosChamadosFechados.resize(400, 466)
        icon = QIcon()
        icon.addFile(u"_img/logo_janela.ico", QSize(), QIcon.Normal, QIcon.Off)
        TelaRelatoriosChamadosFechados.setWindowIcon(icon)
        self.frame = QFrame(TelaRelatoriosChamadosFechados)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 381, 101))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 381, 101))
        self.label.setPixmap(QPixmap(u"_img/banner_relatorio_fechado.png"))
        self.line_2 = QFrame(TelaRelatoriosChamadosFechados)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(90, 120, 291, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_11 = QLabel(TelaRelatoriosChamadosFechados)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 120, 71, 16))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.radio_contrato = QRadioButton(TelaRelatoriosChamadosFechados)
        self.radio_contrato.setObjectName(u"radio_contrato")
        self.radio_contrato.setGeometry(QRect(260, 150, 82, 17))
        self.label_12 = QLabel(TelaRelatoriosChamadosFechados)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 150, 71, 16))
        self.radio_numero_chamado = QRadioButton(TelaRelatoriosChamadosFechados)
        self.radio_numero_chamado.setObjectName(u"radio_numero_chamado")
        self.radio_numero_chamado.setGeometry(QRect(110, 150, 131, 17))
        self.radio_numero_chamado.setChecked(True)
        self.label_2 = QLabel(TelaRelatoriosChamadosFechados)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 180, 111, 16))
        self.label_2.setFont(font)
        self.line = QFrame(TelaRelatoriosChamadosFechados)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(60, 180, 321, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.btn_gerar_data = QPushButton(TelaRelatoriosChamadosFechados)
        self.btn_gerar_data.setObjectName(u"btn_gerar_data")
        self.btn_gerar_data.setGeometry(QRect(270, 222, 101, 31))
        self.label_3 = QLabel(TelaRelatoriosChamadosFechados)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 210, 61, 16))
        self.txt_data_inicial = QLineEdit(TelaRelatoriosChamadosFechados)
        self.txt_data_inicial.setObjectName(u"txt_data_inicial")
        self.txt_data_inicial.setGeometry(QRect(90, 210, 71, 20))
        self.label_4 = QLabel(TelaRelatoriosChamadosFechados)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(180, 210, 71, 16))
        self.label_5 = QLabel(TelaRelatoriosChamadosFechados)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 240, 61, 16))
        self.txt_data_final = QLineEdit(TelaRelatoriosChamadosFechados)
        self.txt_data_final.setObjectName(u"txt_data_final")
        self.txt_data_final.setGeometry(QRect(90, 240, 71, 20))
        self.label_6 = QLabel(TelaRelatoriosChamadosFechados)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(180, 240, 71, 16))
        self.label_7 = QLabel(TelaRelatoriosChamadosFechados)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 270, 41, 16))
        self.label_7.setFont(font)
        self.line_3 = QFrame(TelaRelatoriosChamadosFechados)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(60, 270, 311, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_8 = QLabel(TelaRelatoriosChamadosFechados)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 350, 47, 13))
        self.btn_cancelar = QPushButton(TelaRelatoriosChamadosFechados)
        self.btn_cancelar.setObjectName(u"btn_cancelar")
        self.btn_cancelar.setGeometry(QRect(300, 430, 75, 23))
        self.btn_gerar_status = QPushButton(TelaRelatoriosChamadosFechados)
        self.btn_gerar_status.setObjectName(u"btn_gerar_status")
        self.btn_gerar_status.setGeometry(QRect(270, 350, 101, 23))
        self.label_9 = QLabel(TelaRelatoriosChamadosFechados)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 310, 91, 16))
        self.combo_status = QComboBox(TelaRelatoriosChamadosFechados)
        self.combo_status.addItem("")
        self.combo_status.addItem("")
        self.combo_status.addItem("")
        self.combo_status.addItem("")
        self.combo_status.setObjectName(u"combo_status")
        self.combo_status.setGeometry(QRect(120, 350, 131, 22))
        self.btn_gerar_relatorio_padrao = QPushButton(TelaRelatoriosChamadosFechados)
        self.btn_gerar_relatorio_padrao.setObjectName(u"btn_gerar_relatorio_padrao")
        self.btn_gerar_relatorio_padrao.setGeometry(QRect(160, 430, 131, 23))
        self.combo_tipo = QComboBox(TelaRelatoriosChamadosFechados)
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.addItem("")
        self.combo_tipo.setObjectName(u"combo_tipo")
        self.combo_tipo.setGeometry(QRect(120, 310, 131, 22))
        self.btn_gerar_tipo = QPushButton(TelaRelatoriosChamadosFechados)
        self.btn_gerar_tipo.setObjectName(u"btn_gerar_tipo")
        self.btn_gerar_tipo.setGeometry(QRect(270, 310, 101, 23))
        self.line_4 = QFrame(TelaRelatoriosChamadosFechados)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(20, 400, 361, 20))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)

        self.retranslateUi(TelaRelatoriosChamadosFechados)

        QMetaObject.connectSlotsByName(TelaRelatoriosChamadosFechados)
    # setupUi

    def retranslateUi(self, TelaRelatoriosChamadosFechados):
        TelaRelatoriosChamadosFechados.setWindowTitle(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Form", None))
        self.label.setText("")
        self.label_11.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Ordena\u00e7\u00e3o", None))
        self.radio_contrato.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Contrato", None))
        self.label_12.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Ordenar Por:", None))
        self.radio_numero_chamado.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"N\u00famero do Chamado", None))
        self.label_2.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Datas", None))
        self.btn_gerar_data.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Gerar Relat\u00f3rio", None))
        self.label_3.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Data Inicial:", None))
        self.txt_data_inicial.setInputMask(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"##/##/####", None))
        self.label_4.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"dd/MM/yyyy", None))
        self.label_5.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Data Final:", None))
        self.txt_data_final.setInputMask(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"##/##/####", None))
        self.label_6.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"dd/MM/yyyy", None))
        self.label_7.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Filtros", None))
        self.label_8.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Status:", None))
        self.btn_cancelar.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Cancelar", None))
        self.btn_gerar_status.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Gerar Relat\u00f3rio", None))
        self.label_9.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Tipo do Chamado:", None))
        self.combo_status.setItemText(0, QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Selecione uma op\u00e7\u00e3o", None))
        self.combo_status.setItemText(1, QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Fechado", None))
        self.combo_status.setItemText(2, QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Reagendado", None))
        self.combo_status.setItemText(3, QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Cancelado", None))

        self.btn_gerar_relatorio_padrao.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Gerar Relat\u00f3rio padr\u00e3o", None))
        self.combo_tipo.setItemText(0, QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Selecione uma op\u00e7\u00e3o", None))
        self.combo_tipo.setItemText(1, QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Incidente", None))
        self.combo_tipo.setItemText(2, QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Cobran\u00e7a", None))
        self.combo_tipo.setItemText(3, QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"D\u00favida", None))

        self.btn_gerar_tipo.setText(QCoreApplication.translate("TelaRelatoriosChamadosFechados", u"Gerar Relat\u00f3rio", None))
    # retranslateUi

