# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_tela_principal.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_TelaPrincipal(object):
    def setupUi(self, TelaPrincipal):
        if not TelaPrincipal.objectName():
            TelaPrincipal.setObjectName(u"TelaPrincipal")
        TelaPrincipal.resize(1075, 659)
        icon = QIcon()
        icon.addFile(u"_img/logo_janela.ico", QSize(), QIcon.Normal, QIcon.Off)
        TelaPrincipal.setWindowIcon(icon)
        self.menu_usuarios = QAction(TelaPrincipal)
        self.menu_usuarios.setObjectName(u"menu_usuarios")
        icon1 = QIcon()
        icon1.addFile(u"_img/user.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_usuarios.setIcon(icon1)
        self.actionCadastro_Parceiro = QAction(TelaPrincipal)
        self.actionCadastro_Parceiro.setObjectName(u"actionCadastro_Parceiro")
        self.menu_sair = QAction(TelaPrincipal)
        self.menu_sair.setObjectName(u"menu_sair")
        icon2 = QIcon()
        icon2.addFile(u"_img/sair.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_sair.setIcon(icon2)
        self.menu_clientes = QAction(TelaPrincipal)
        self.menu_clientes.setObjectName(u"menu_clientes")
        icon3 = QIcon()
        icon3.addFile(u"_img/cliente.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_clientes.setIcon(icon3)
        self.menu_consultar_clientes = QAction(TelaPrincipal)
        self.menu_consultar_clientes.setObjectName(u"menu_consultar_clientes")
        icon4 = QIcon()
        icon4.addFile(u"_img/consulta.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_consultar_clientes.setIcon(icon4)
        self.menu_solucoes = QAction(TelaPrincipal)
        self.menu_solucoes.setObjectName(u"menu_solucoes")
        icon5 = QIcon()
        icon5.addFile(u"_img/solucoes.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_solucoes.setIcon(icon5)
        self.menu_parceiro = QAction(TelaPrincipal)
        self.menu_parceiro.setObjectName(u"menu_parceiro")
        icon6 = QIcon()
        icon6.addFile(u"_img/parceiro.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_parceiro.setIcon(icon6)
        self.menu_novo_chamado = QAction(TelaPrincipal)
        self.menu_novo_chamado.setObjectName(u"menu_novo_chamado")
        icon7 = QIcon()
        icon7.addFile(u"_img/chamado.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_novo_chamado.setIcon(icon7)
        self.menu_consulta_chamado = QAction(TelaPrincipal)
        self.menu_consulta_chamado.setObjectName(u"menu_consulta_chamado")
        icon8 = QIcon()
        icon8.addFile(u"_img/pesquisa_chamado.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_consulta_chamado.setIcon(icon8)
        self.menu_fechamento_de_Chamados = QAction(TelaPrincipal)
        self.menu_fechamento_de_Chamados.setObjectName(u"menu_fechamento_de_Chamados")
        icon9 = QIcon()
        icon9.addFile(u"_img/fechamento_chamado.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_fechamento_de_Chamados.setIcon(icon9)
        self.menu_Consulta_de_Chamados_Fechados = QAction(TelaPrincipal)
        self.menu_Consulta_de_Chamados_Fechados.setObjectName(u"menu_Consulta_de_Chamados_Fechados")
        icon10 = QIcon()
        icon10.addFile(u"_img/consulta_chamado_fechado.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_Consulta_de_Chamados_Fechados.setIcon(icon10)
        self.menu_novo_Chamado_Parceiro = QAction(TelaPrincipal)
        self.menu_novo_Chamado_Parceiro.setObjectName(u"menu_novo_Chamado_Parceiro")
        icon11 = QIcon()
        icon11.addFile(u"_img/abrir_chamado_parceiro.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_novo_Chamado_Parceiro.setIcon(icon11)
        self.menu_consultar_Chamado_Parceiro = QAction(TelaPrincipal)
        self.menu_consultar_Chamado_Parceiro.setObjectName(u"menu_consultar_Chamado_Parceiro")
        icon12 = QIcon()
        icon12.addFile(u"_img/consultar_chamado_parceiro.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_consultar_Chamado_Parceiro.setIcon(icon12)
        self.menu_fechar_Chamado_Parceiro = QAction(TelaPrincipal)
        self.menu_fechar_Chamado_Parceiro.setObjectName(u"menu_fechar_Chamado_Parceiro")
        icon13 = QIcon()
        icon13.addFile(u"_img/fechar_chamado_parceiro.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_fechar_Chamado_Parceiro.setIcon(icon13)
        self.menu_consultar_chamado_parceiro_fechado = QAction(TelaPrincipal)
        self.menu_consultar_chamado_parceiro_fechado.setObjectName(u"menu_consultar_chamado_parceiro_fechado")
        self.menu_consultar_chamado_parceiro_fechado.setIcon(icon12)
        self.menu_relatorios_chamados = QAction(TelaPrincipal)
        self.menu_relatorios_chamados.setObjectName(u"menu_relatorios_chamados")
        icon14 = QIcon()
        icon14.addFile(u"_img/relatorio.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_relatorios_chamados.setIcon(icon14)
        self.menu_relatorios_chamados_fechados = QAction(TelaPrincipal)
        self.menu_relatorios_chamados_fechados.setObjectName(u"menu_relatorios_chamados_fechados")
        icon15 = QIcon()
        icon15.addFile(u"_img/relatorio-chamados_fechados.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_relatorios_chamados_fechados.setIcon(icon15)
        self.menu_ajuda = QAction(TelaPrincipal)
        self.menu_ajuda.setObjectName(u"menu_ajuda")
        icon16 = QIcon()
        icon16.addFile(u"_img/help.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_ajuda.setIcon(icon16)
        self.centralwidget = QWidget(TelaPrincipal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setStyleSheet(u"")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setPixmap(QPixmap(u"_img/fundo_tela_principal2.png"))
        self.label_2.setScaledContents(True)

        self.horizontalLayout_2.addWidget(self.label_2)


        self.verticalLayout_2.addWidget(self.frame_2)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        sizePolicy1 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.horizontalLayout.addWidget(self.label)

        self.lbl_usuario = QLabel(self.frame)
        self.lbl_usuario.setObjectName(u"lbl_usuario")
        self.lbl_usuario.setFont(font)
        self.lbl_usuario.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.horizontalLayout.addWidget(self.lbl_usuario)


        self.verticalLayout.addLayout(self.horizontalLayout)


        self.verticalLayout_2.addWidget(self.frame)

        TelaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TelaPrincipal)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1075, 21))
        self.menuArquivo = QMenu(self.menubar)
        self.menuArquivo.setObjectName(u"menuArquivo")
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setWeight(50)
        self.menuArquivo.setFont(font1)
        self.menuArquivo.setStyleSheet(u"Arquivo")
        self.menuArquivo.setTearOffEnabled(False)
        self.menuArquivo.setSeparatorsCollapsible(False)
        self.menuArquivo.setToolTipsVisible(False)
        self.menuClientes = QMenu(self.menubar)
        self.menuClientes.setObjectName(u"menuClientes")
        self.menuChamados = QMenu(self.menubar)
        self.menuChamados.setObjectName(u"menuChamados")
        self.menuChamado_Parceiro = QMenu(self.menubar)
        self.menuChamado_Parceiro.setObjectName(u"menuChamado_Parceiro")
        self.menuRelat_rios = QMenu(self.menubar)
        self.menuRelat_rios.setObjectName(u"menuRelat_rios")
        self.menuAjuda = QMenu(self.menubar)
        self.menuAjuda.setObjectName(u"menuAjuda")
        TelaPrincipal.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(TelaPrincipal)
        self.statusbar.setObjectName(u"statusbar")
        TelaPrincipal.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(TelaPrincipal)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setIconSize(QSize(32, 32))
        TelaPrincipal.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuClientes.menuAction())
        self.menubar.addAction(self.menuChamados.menuAction())
        self.menubar.addAction(self.menuChamado_Parceiro.menuAction())
        self.menubar.addAction(self.menuRelat_rios.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())
        self.menuArquivo.addAction(self.menu_usuarios)
        self.menuArquivo.addAction(self.menu_solucoes)
        self.menuArquivo.addAction(self.menu_parceiro)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.menu_sair)
        self.menuClientes.addAction(self.menu_clientes)
        self.menuClientes.addAction(self.menu_consultar_clientes)
        self.menuChamados.addAction(self.menu_novo_chamado)
        self.menuChamados.addAction(self.menu_consulta_chamado)
        self.menuChamados.addAction(self.menu_fechamento_de_Chamados)
        self.menuChamados.addAction(self.menu_Consulta_de_Chamados_Fechados)
        self.menuChamado_Parceiro.addAction(self.menu_novo_Chamado_Parceiro)
        self.menuChamado_Parceiro.addAction(self.menu_consultar_Chamado_Parceiro)
        self.menuChamado_Parceiro.addAction(self.menu_fechar_Chamado_Parceiro)
        self.menuChamado_Parceiro.addAction(self.menu_consultar_chamado_parceiro_fechado)
        self.menuRelat_rios.addAction(self.menu_relatorios_chamados)
        self.menuRelat_rios.addAction(self.menu_relatorios_chamados_fechados)
        self.menuAjuda.addAction(self.menu_ajuda)
        self.toolBar.addAction(self.menu_usuarios)
        self.toolBar.addAction(self.menu_solucoes)
        self.toolBar.addAction(self.menu_parceiro)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.menu_clientes)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.menu_novo_chamado)
        self.toolBar.addAction(self.menu_consulta_chamado)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.menu_fechamento_de_Chamados)
        self.toolBar.addAction(self.menu_Consulta_de_Chamados_Fechados)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.menu_novo_Chamado_Parceiro)
        self.toolBar.addAction(self.menu_fechar_Chamado_Parceiro)
        self.toolBar.addAction(self.menu_consultar_chamado_parceiro_fechado)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.menu_relatorios_chamados)
        self.toolBar.addAction(self.menu_relatorios_chamados_fechados)

        self.retranslateUi(TelaPrincipal)

        QMetaObject.connectSlotsByName(TelaPrincipal)
    # setupUi

    def retranslateUi(self, TelaPrincipal):
        TelaPrincipal.setWindowTitle(QCoreApplication.translate("TelaPrincipal", u"MainWindow", None))
        self.menu_usuarios.setText(QCoreApplication.translate("TelaPrincipal", u"Usuarios", None))
        self.actionCadastro_Parceiro.setText(QCoreApplication.translate("TelaPrincipal", u"Cadastro Parceiro", None))
        self.menu_sair.setText(QCoreApplication.translate("TelaPrincipal", u"Sair", None))
        self.menu_clientes.setText(QCoreApplication.translate("TelaPrincipal", u"Novo Cliente", None))
        self.menu_consultar_clientes.setText(QCoreApplication.translate("TelaPrincipal", u"Consultar Clientes", None))
        self.menu_solucoes.setText(QCoreApplication.translate("TelaPrincipal", u"Solu\u00e7\u00f5es", None))
        self.menu_parceiro.setText(QCoreApplication.translate("TelaPrincipal", u"Parceiro", None))
        self.menu_novo_chamado.setText(QCoreApplication.translate("TelaPrincipal", u"Novo Chamado", None))
        self.menu_consulta_chamado.setText(QCoreApplication.translate("TelaPrincipal", u"Consultar Chamado", None))
        self.menu_fechamento_de_Chamados.setText(QCoreApplication.translate("TelaPrincipal", u"Fechamento de Chamados", None))
        self.menu_Consulta_de_Chamados_Fechados.setText(QCoreApplication.translate("TelaPrincipal", u"Consulta de Chamados Fechados", None))
        self.menu_novo_Chamado_Parceiro.setText(QCoreApplication.translate("TelaPrincipal", u"Novo Chamado Parceiro", None))
        self.menu_consultar_Chamado_Parceiro.setText(QCoreApplication.translate("TelaPrincipal", u"Consultar Chamado Parceiro", None))
        self.menu_fechar_Chamado_Parceiro.setText(QCoreApplication.translate("TelaPrincipal", u"Fechar Chamado Parceiro", None))
        self.menu_consultar_chamado_parceiro_fechado.setText(QCoreApplication.translate("TelaPrincipal", u"Consultar chamado parceiro fechado", None))
        self.menu_relatorios_chamados.setText(QCoreApplication.translate("TelaPrincipal", u"Gerar Relat\u00f3rios de Chamados", None))
        self.menu_relatorios_chamados_fechados.setText(QCoreApplication.translate("TelaPrincipal", u"Gerar Relat\u00f3rios de Chamados encerrados", None))
        self.menu_ajuda.setText(QCoreApplication.translate("TelaPrincipal", u"Sobre", None))
        self.label_2.setText("")
        self.label.setText(QCoreApplication.translate("TelaPrincipal", u"Usuario:", None))
        self.lbl_usuario.setText("")
        self.menuArquivo.setTitle(QCoreApplication.translate("TelaPrincipal", u"Cadastro", None))
        self.menuClientes.setTitle(QCoreApplication.translate("TelaPrincipal", u"Clientes", None))
        self.menuChamados.setTitle(QCoreApplication.translate("TelaPrincipal", u"Chamados", None))
        self.menuChamado_Parceiro.setTitle(QCoreApplication.translate("TelaPrincipal", u"Chamado Parceiro", None))
        self.menuRelat_rios.setTitle(QCoreApplication.translate("TelaPrincipal", u"Relat\u00f3rios", None))
        self.menuAjuda.setTitle(QCoreApplication.translate("TelaPrincipal", u"Ajuda", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("TelaPrincipal", u"toolBar", None))
    # retranslateUi

