# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_relatorio_chamados.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_RelatorioChamado(object):
    def setupUi(self, RelatorioChamado):
        if not RelatorioChamado.objectName():
            RelatorioChamado.setObjectName(u"RelatorioChamado")
        RelatorioChamado.resize(400, 466)
        icon = QIcon()
        icon.addFile(u"_img/logo_janela.ico", QSize(), QIcon.Normal, QIcon.Off)
        RelatorioChamado.setWindowIcon(icon)
        self.frame = QFrame(RelatorioChamado)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 381, 80))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 0, 381, 81))
        self.label_10.setPixmap(QPixmap(u"_img/banner_relatorio_chamados.png"))
        self.label = QLabel(RelatorioChamado)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 170, 111, 16))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.line = QFrame(RelatorioChamado)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(60, 170, 321, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_2 = QLabel(RelatorioChamado)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 210, 61, 16))
        self.txt_data = QLineEdit(RelatorioChamado)
        self.txt_data.setObjectName(u"txt_data")
        self.txt_data.setGeometry(QRect(90, 210, 71, 20))
        self.label_4 = QLabel(RelatorioChamado)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(180, 210, 71, 16))
        self.btn_cancelar = QPushButton(RelatorioChamado)
        self.btn_cancelar.setObjectName(u"btn_cancelar")
        self.btn_cancelar.setGeometry(QRect(310, 420, 75, 23))
        self.label_7 = QLabel(RelatorioChamado)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 250, 41, 16))
        self.label_7.setFont(font)
        self.line_3 = QFrame(RelatorioChamado)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(70, 250, 311, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_8 = QLabel(RelatorioChamado)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 280, 81, 16))
        self.combo_solucao = QComboBox(RelatorioChamado)
        self.combo_solucao.addItem("")
        self.combo_solucao.setObjectName(u"combo_solucao")
        self.combo_solucao.setGeometry(QRect(120, 280, 131, 22))
        self.label_9 = QLabel(RelatorioChamado)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 320, 91, 16))
        self.combo_tipo_chamado = QComboBox(RelatorioChamado)
        self.combo_tipo_chamado.addItem("")
        self.combo_tipo_chamado.addItem("")
        self.combo_tipo_chamado.addItem("")
        self.combo_tipo_chamado.addItem("")
        self.combo_tipo_chamado.setObjectName(u"combo_tipo_chamado")
        self.combo_tipo_chamado.setGeometry(QRect(120, 320, 131, 22))
        self.label_6 = QLabel(RelatorioChamado)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 360, 47, 13))
        self.combo_status = QComboBox(RelatorioChamado)
        self.combo_status.addItem("")
        self.combo_status.addItem("")
        self.combo_status.addItem("")
        self.combo_status.addItem("")
        self.combo_status.setObjectName(u"combo_status")
        self.combo_status.setGeometry(QRect(120, 360, 131, 22))
        self.label_11 = QLabel(RelatorioChamado)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 110, 71, 16))
        self.label_11.setFont(font)
        self.line_2 = QFrame(RelatorioChamado)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(90, 110, 291, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_12 = QLabel(RelatorioChamado)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 140, 71, 16))
        self.btn_gerar_solucao = QPushButton(RelatorioChamado)
        self.btn_gerar_solucao.setObjectName(u"btn_gerar_solucao")
        self.btn_gerar_solucao.setGeometry(QRect(270, 280, 101, 23))
        self.btn_gerar_tipo = QPushButton(RelatorioChamado)
        self.btn_gerar_tipo.setObjectName(u"btn_gerar_tipo")
        self.btn_gerar_tipo.setGeometry(QRect(270, 320, 101, 23))
        self.btn_gerar_status = QPushButton(RelatorioChamado)
        self.btn_gerar_status.setObjectName(u"btn_gerar_status")
        self.btn_gerar_status.setGeometry(QRect(270, 360, 101, 23))
        self.radio_numero_chamado = QRadioButton(RelatorioChamado)
        self.radio_numero_chamado.setObjectName(u"radio_numero_chamado")
        self.radio_numero_chamado.setGeometry(QRect(90, 140, 131, 17))
        self.radio_numero_chamado.setChecked(True)
        self.radio_contrato = QRadioButton(RelatorioChamado)
        self.radio_contrato.setObjectName(u"radio_contrato")
        self.radio_contrato.setGeometry(QRect(240, 140, 82, 17))
        self.btn_gerar_data = QPushButton(RelatorioChamado)
        self.btn_gerar_data.setObjectName(u"btn_gerar_data")
        self.btn_gerar_data.setGeometry(QRect(270, 210, 101, 23))
        self.btn_gerar_relatorio_padrao = QPushButton(RelatorioChamado)
        self.btn_gerar_relatorio_padrao.setObjectName(u"btn_gerar_relatorio_padrao")
        self.btn_gerar_relatorio_padrao.setGeometry(QRect(170, 420, 131, 23))

        self.retranslateUi(RelatorioChamado)

        QMetaObject.connectSlotsByName(RelatorioChamado)
    # setupUi

    def retranslateUi(self, RelatorioChamado):
        RelatorioChamado.setWindowTitle(QCoreApplication.translate("RelatorioChamado", u"Form", None))
        self.label_10.setText("")
        self.label.setText(QCoreApplication.translate("RelatorioChamado", u"Datas", None))
        self.label_2.setText(QCoreApplication.translate("RelatorioChamado", u"Data Inicial:", None))
        self.txt_data.setInputMask(QCoreApplication.translate("RelatorioChamado", u"##/##/####", None))
        self.label_4.setText(QCoreApplication.translate("RelatorioChamado", u"dd/MM/yyyy", None))
        self.btn_cancelar.setText(QCoreApplication.translate("RelatorioChamado", u"Cancelar", None))
        self.label_7.setText(QCoreApplication.translate("RelatorioChamado", u"Filtros", None))
        self.label_8.setText(QCoreApplication.translate("RelatorioChamado", u"Solu\u00e7\u00e3o:", None))
        self.combo_solucao.setItemText(0, QCoreApplication.translate("RelatorioChamado", u"Selecione uma op\u00e7\u00e3o", None))

        self.label_9.setText(QCoreApplication.translate("RelatorioChamado", u"Tipo do Chamado:", None))
        self.combo_tipo_chamado.setItemText(0, QCoreApplication.translate("RelatorioChamado", u"Selecione uma op\u00e7\u00e3o", None))
        self.combo_tipo_chamado.setItemText(1, QCoreApplication.translate("RelatorioChamado", u"Incidente", None))
        self.combo_tipo_chamado.setItemText(2, QCoreApplication.translate("RelatorioChamado", u"Cobran\u00e7a", None))
        self.combo_tipo_chamado.setItemText(3, QCoreApplication.translate("RelatorioChamado", u"D\u00favida", None))

        self.label_6.setText(QCoreApplication.translate("RelatorioChamado", u"Status:", None))
        self.combo_status.setItemText(0, QCoreApplication.translate("RelatorioChamado", u"Selecione uma op\u00e7\u00e3o", None))
        self.combo_status.setItemText(1, QCoreApplication.translate("RelatorioChamado", u"Aberto", None))
        self.combo_status.setItemText(2, QCoreApplication.translate("RelatorioChamado", u"Em Atendimento", None))
        self.combo_status.setItemText(3, QCoreApplication.translate("RelatorioChamado", u"Cancelado", None))

        self.label_11.setText(QCoreApplication.translate("RelatorioChamado", u"Ordena\u00e7\u00e3o", None))
        self.label_12.setText(QCoreApplication.translate("RelatorioChamado", u"Ordenar Por:", None))
        self.btn_gerar_solucao.setText(QCoreApplication.translate("RelatorioChamado", u"Gerar Relat\u00f3rio", None))
        self.btn_gerar_tipo.setText(QCoreApplication.translate("RelatorioChamado", u"Gerar Relat\u00f3rio", None))
        self.btn_gerar_status.setText(QCoreApplication.translate("RelatorioChamado", u"Gerar Relat\u00f3rio", None))
        self.radio_numero_chamado.setText(QCoreApplication.translate("RelatorioChamado", u"N\u00famero do Chamado", None))
        self.radio_contrato.setText(QCoreApplication.translate("RelatorioChamado", u"Contrato", None))
        self.btn_gerar_data.setText(QCoreApplication.translate("RelatorioChamado", u"Gerar Relat\u00f3rio", None))
        self.btn_gerar_relatorio_padrao.setText(QCoreApplication.translate("RelatorioChamado", u"Gerar Relat\u00f3rio padr\u00e3o", None))
    # retranslateUi

